---
title: Blackened Salmon Tacos
description: Blackened Salmon Tacos with Avocado Mango Salsa and Cilantro Avacado Dressing
categories: [Lunch, Dinner]
cooktime: 1 hour
date: 2024-12-24
---

## Ingredients

### Salsa

- 1 large avocado, cubed
- 1 mango, cubed
- 1 orange bell pepper, diced
- 1 jalapeno, diced
- 1/3 cup cilantro, chopped
- Juice from 1 lime Salt and pepper, to taste Green cholula, to taste 2 cloves garlic, grated

Combine all ingredients in a bowl and mix. Taste for seasonings. Refrigerate until it's time to eat.

### Seasoning

- 1/2 tosp paprika
- 1/2 tosp smoked paprika
- 1/2 tosp garlic powder
- 1/2 tbsp onion powder
- 1.5 tsp salt (to taste)
- 1.5 tsp black pepper (to taste)
- 1.5 tsp dried thyme
- 1.5 tsp dried oregano
- 1.5 tsp dried basil
- Dash of cayenne, optional (about 1/4 tsp)

Combine all ingredients in a bowl and mix then set aside.

### Avacado Sauce

- 1/4 cup water (more or less)
- Handful of cilantro (about 1 cup)
- 1-2 cloves garlic
- 1/2 large avocado (or one small)
- 1/4 cup greek yogurt (more or less)
- Juice from 1 lime
- Salt and pepper, to tase Green cholula, to taste

Combine all ingredients in a blender and blend until smooth. Taste for seasonings. You might need to add more water, greek yogurt, garlic, salt, etc. This one I tend to keep adding until I get the taste and consistency I want. Refrigerate until it's time to eat.

### Tacos

- 2 large salmon filets
- Tortillas
- Lime wedge & cilantro for serving

## Directions

1. Preheat oven to 425F and take your salmon out of the fridge
2. Once the oven is ready, coat your salmon in olive oil and generously season with your blackened seasoning on all sides. Bake at 425F for 20 minutes (depending on your desired doneness)
3. While your salmon cooks, toast your corn tortillas in a pan over medium heat with a touch of olive oil. You don't want them to get super crispy, but just a nice golden toast is perfect.
4. When the salmon is done, it's time to assemble your tacos. Add a layer of your avocado sauce, flakey salmon, mango salsa, and top with extra lime juice, avacado sauce, and green cholula. Serve with a side of lime wedges and cilantro. Enjoy!
