---
title: Italian Wedding Soup
description: Italian Wedding Soup
categories: [Soup,Lunch,Dinner]
cooktime: 1 hour
date: 2024-12-23
---

## Ingredients

### Meatballs

- 1/2 Ib ground beef
- 1/2 Ib ground pork
- 1/4 cup parsley, chopped
- 3-4 basil leaves,
- Salt and pepper, to taste
- 1 tsp dried oregano
- 1 tsp calabrian chili paste (or red pepper)
- 1 egg, beaten
- 2-3 cloves garlic, grated
- 1/2 cup Parmesan cheese, grated
- 1 cup day-old bread, torn into pieces
- 1/4 cup milk (to soak the bread)
- Olive oil (for searing)

### Soup

- 1 tbsp olive oil
- 1 medium onion, diced
- 2 stalks celery, diced
- 2 stalks carrots, diced
- 1 tosp Italian seasoning
- 1-2 tsp calabrian chili paste, to taste
- 6 cloves garlic, minced, to taste
- 1/2 cup dry white wine
- 8 cups chicken broth
- Parmesan rind
- Bay leaf
- Rosemary sprig
- Few thyme sprigs
- 1 cup acini di pepe (or other small pasta)
- 2 cups fresh spinach (or kale)
- 1/2 cup parmesan
- Salt and pepper, to taste

## Directions

1. In a bowl, soak the torn day-old bread in milk for 5-10 minutes. Squeeze out excess liquid.
2. Combine the soaked bread, beef, pork, parsley, basil, salt, pepper, oregano, calabrian chili, garlic, egg, and Parmesan. Mix until just combined.
3. Form the mixture into small meatballs and place them on a tray or plate.
4. Heat a large soup pot over medium heat and add 1 tosp olive oil.
5. Brown the meatballs in batches (don't overcrowd the pot), turning occasionally, need to be fully Cooked. Remove from the pot and set aside. Add oil in between batches if needed.
6. In the same pot, heat another tbsp of olive oil over medium heat. Add the chopped onion, carrots, celery, salt, pepper, oregano, and calabrian chili. Sauté for 5-7 minutes until theg soup vegetables soften.
7. Stir in the minced garlic and cook for 30 seconds.
8. Pour in the wine, if using, and let simmer for 2-3 minutes.
9. Pour in the chicken broth, season with salt and pepper, and bring it to a simmer.
10. Gently drop the meatballs into the broth. Add in the parmesan rind, bay leaf, rosemary, and thyme. Simmer for 8-10 minutes.
11. Pour in the acini di pepe and simmer for another 10 minutes, or untihthe pasta is tender.Italian wedding soup
12. Add the fresh spinach and stir until wilted.
13. Add the parmesan cheese and taste for seasonings.
14. Serve with extra parmesan and fresh parsley or basil. Enjoy!
