---
title: Lasagna Soup
description: Lasagna soup
categories: [Soup, Lunch, Dinner]
cooktime: 30 minutes
date: 2023-12-24
---

## Ingredients

### Soup

- 1-2 teaspoons Tony’s Seasoning (to taste)
- 1/2 yellow onion, diced (about a cup)
- 6-8 cloves minced garlic, to taste
- 1/2 lb hot or mild Italian sausage (I used hot)
- 1/2 lb lean ground beef
- 2 tbsp tomato paste
- Salt and pepper to taste
- 1 teaspoon dried basil
- 1 teaspoon dried parsley
- 1 teaspoon dried oregano
- 1 teaspoon Italian seasoning
- 1/2 teaspoon red pepper (to taste)
- 24 oz marinara
- 1/2 cup heavy cream
- 4-6 cups chicken stock, depending on how soupy you want it
- 1/2 lb lasagna noodles, broken into pieces
- Handful of fresh basil

### Ricotta Mixture

- 1 cup parm
- 1 cup ricotta
- 1 cup mozzarella
- 1/4 cup fresh parsley
- Salt and pepper to taste

## Directions

1. In a medium bowl, combine your parmesan, ricotta, mozzarella, parsley, salt and pepper. Set aside.
2. In a large soup pot or dutch oven, heat your olive oil over medium heat. Add in your onion, add a pinch of salt, and cook for 4 minutes. Throw in your garlic and cook until fragrant, about 30 seconds.
3. Add in your sausage and beef, breaking into pieces with a wooden spoon. Cook for a few minutes and then season with your salt, pepper, basil, oregano, parsley, Italian, and red pepper. Cook until no longer pink.
4. Add in your tomato paste and stir. Cook for a couple minutes. Pour in your chicken broth and marinara. Bring to a boil.
5. Pour in your lasagna pieces, reduce heat, and simmer for about 10 minutes, or until al dente, stirring occasionally. Once your noodles are done, add in your heavy cream and fresh basil (torn). Adjust seasonings if needed. Stir, serve, and top with a dollop of your ricotta mixture. Enjoy!
