---
title: Roasted Feta and Red Pepper Soup
description: Roasted feta and red pepper soup
categories: [Soup, Lunch, Dinner]
cooktime: 1 hour
date: 2024-12-24
---

## Ingredients

- Olive oil
- 4 large red bell peppers, halved and seeded
- 6 garlic cloves, unpeeled
- 8oz block Athenos Feta cheese
- crumbed Feta, to top 1 medium yellow onion, diced
- 2 stalks celery, diced
- 2 medium carrots, diced
- 1 tsp dried thyme
- 1 tsp red pepper flakes, to taste ta ?
- ½ teaspoon smoked paprika
- ½ cup dry white wine (sav blanc)
- 4 cups low-sodium vegetable broth
- 28oz can crushed
- 1 medium yukon potato, peeled and diced
- Juice from 1 lemon, to taste
- Salt and freshly ground black pepper, to taste

Garnish: crumbled Feta, thyme, lemon zest, black pepper, olive

## Directions

1. Preheat oven to 400°F.
2. Place Athenos Feta chunk, halved bell peppers (cut side down), and garlic on a baking sheet lined with parchment paper. Drizzle everything with a bit of olive oil and season with salt and pepper. Roast for 25-30 minutes, or until the peppers are soft and the skins are blistered.
3. While the vegetables are roasting, heat 1 tablespoon of olive oil in a large pot over medium heat. Add the diced onion, celery, carrots, thyme, red pepper, paprika, and salt and pepper. Sauté for 5-7 minutes until softened.
4. Pour in the white wine and cook for 2-3 minutes.
5. Add the diced potato, crushed tomatoes, and vegetable broth to the pot. Season with a pinch of salt. Bring to a boil and simmer for about 15-20 minutes, or until the potatoes are fork-tender.
6. Once the potatoes are tender, carefully blend the soup with an immersion blender or in batches with a heat-safe blender. Return to the pot
7. Once the roasted feta and peppers are done, let them cool slightly. Peel the skins off the peppers (if desired) and squeeze the roasted garlic cloves out of their skins. Blend until smooth and add to the pot.
8. Add in the lemon juice and adjust seasonings as needed.
9. Ladle the soup into bowls and garnish with crumbled feta, fresh herbs, a drizzle of olive oil, and cracked black pepper. Serve with crusty bread or a grilled cheese and enjoy.
