---
title: Simple Salad Dressing
description: Simple salad dressing
categories: [Dip/Sauce, Dressing]
cooktime: 10 minutes
date: 2024-12-24
---

The key to remember is that the oil and vinegar should be in a 3:1 ratio. This recipe is a great base to start with, but feel free to adjust the seasonings to your liking.

You can use whatever vinegar you like, just make sure to add something to bind the oil and vinegar together. I like to use dijon in this recipe, but it's also delicious with mayo. I like to season mine with honey (optional), salt, pepper, grated garlic and Italian seasoning, but a touch of parmesan and shallot would be delicious as well. The best part is you can really make it your own. Just follow the ratio as a guide.

## Ingredients

- 3 tosp good olive oil
- 1 tosp vinegar (lemon juice)
- 1 tsp dijon mustard
- 1 tsp honey (optional)
- Salt and pepper, to taste (about 1/4-1/2 tsp each)
- 1/2 - 1 tsp Italian seasoning
- Grated garlic, 2 cloves

## Directions

1. In a mason jar or a jar with a lid combine all your ingredients. Cover and shake until emulsified. Taste for seasoning (sometimes I add a touch of extra salt and honey). Refrigerate for up to 1 week!

**NOTE**: If using a bowl and a whisk, add in all ingredients except your oil. Stir to combine. Slowly drizzle in your oil, whisking continuously until emulsified. Taste for seasoning and adjust as needed.
