---
title: Vodka Pasta
description: Vodka pasta
categories: [Lunch, Dinner]
cooktime: 30 minutes
date: 2023-11-24
---

## Ingredients

- 1 lb pasta of choice (reserve pasta water)
- 2 tablespoons olive oil
- 2 tablespoons butter
- 1 shallot diced
- 2-3 garlic cloves, grated
- 1 tablespoon red pepper (to taste)
- 1-2 teaspoons salt (to taste)
- 1 teaspoon black pepper (to taste)
- 1 teaspoon oregano (optional)
- 1 tube tomato pasta (4.5 oz)
- 50 ml vodka (a little less than 1/3 cup)
- 1 cup heavy cream
- 1 cup parmesan cheese, freshly grated
- Fresh basil and parmesan to garnish

## Directions

1. Boil your pasta in heavily salted water, 3 minutes less than package instructions. You want the pasta to finish cooking in the sauce
2. In a large saucepan, heat olive oil and 1T of butter over medium heat. Add in your shallot, garlic, and seasonings. Cook for about 3 minutes, stirring frequently.
3. Add in your tomato paste and stir. Cook for about 3-4 minutes (don’t skip this step, you need to cook off the tomato paste before adding the vodka)
4. Pour in your pasta and stir to combine. Simmer for a couple of minutes.
5. Reduce heat to low. Add in your cream and remaining butter, stir to combine.
6. Add in your cooked pasta along with about 1/2 cup pasta water. Stir for a few minutes to get that silky smooth sauce.
7. Adjust your seasonings, add in your parm, and a little extra butter. Top with more parm and fresh basil.
