---
title: White Chicken Chili
description: White chicken chili
categories: [Soup, Lunch, Dinner]
cooktime: 30 minutes
date: 2024-12-24
---

## Ingredients

- 2 tbsp olive oil
- 1 large yellow onion, diced
- 1 jalapeño, diced (optional for spice)
- 1 head of garlic, minced, to taste
- 3 to 4 cups low-sodium chicken broth (depending on how liquidy you want it)
- 2, 15.5oz can Bush's Slow Simmered White Chili Magic
- 1 rotisserie chicken, shredded
- 1 (16 oz) jar Salsa Verde, mild or medium
- 1/4 cup cilantro, to taste
- Juice from 1 lime, plus more for topping
- 1/2 cup sour cream, plus more for topping

Toppings: lime juice, sour cream, avocado, shredded cheese, crumbled tortillas strips, cilantro, jalapeño.

## Directions

1. In a large Dutch oven or soup pot, heat your butter and olive oil.
2. Add in your onion and jalapeno pepper. Sauté for 5-7 minutes. Add in your garlic and cook for another minute.
3. Pour in your chicken broth, shredded chicken, salsa verde, and Bush's Chili Magic. Stir and bring to a boil. Reduce heat to low, partially cover, and simmer for as long as you're patient for at least 20
4. Turn off the heat and add in your cilantro, lime juice, and sour cream. Stir and serve immediately. Top with lime juice, cheese, sour cream, avocado, cilantro, and tortilla chips.
