---
title: Wonton Soup
description: Deconstructed Wonton Soup
categories: [Soup]
cooktime: 1 hour
date: 2024-12-24
---

## Ingredients

### Meatballs

- 1 lb ground pork
- 4 stalks green onion, diced (plus more for garnish)
- 2 tsp grated ginger
- 3 cloves grated garlic
- 2 tbsp soy sauce
- 2 tsp sesame oil
- 2 tsp rice vinegar
- 1 tsp white pepper
- 2 tosp cornstarch

### Broth

- 6 cups chicken broth
- 5-6 cloves garlic, smashed (to taste)
- 1-inch piece ginger, sliced
- 1 onion, quartered
- 1 tosp lemongrass paste (can use fresh)
- 1-2 tbsp soy sauce (to taste)
- 1 tosp sesame oil (to taste)
- 1 tbsp rice vinegar (to taste)
- 1 tsp white pepper
- Pinch of salt (to taste)
- 1-2 teaspoons fish sauce (optional)
- 16-20 wonton wrappers, cut in 4
- 6 baby bok choy, rinsed and chopped Chili oil (for garnish) I used

## Directions

1. In a mixing bowl, combine the ground pork, green onion, ginger, garlic, soy sauce, sesame oil, white pepper, rice vinegar, and cornstarch. Mix until just combined and form into small meatballs, about 1 inch in diameter. Set aside.
2. In a large pot, heat about 1 tbsp of sesame oil over medium heat. Add the onion, smashed garlic, sliced ginger, and lemongrass paste. Sauté for 3-4 minutes, until the aromatics are fragrant. (you might need to add a drizzle of olive oil to prevent
3. Pour in the chicken broth and season with soy sauce, rice vinegar, sesame oil, white pepper, pinch of salt, and fish sauce (if using). Bring to a boil, then reduce heat and simmer for 20 min.
4. Strain the broth to remove the onion, garlic and ginger.
5. Return the broth to the pot and bring it back to a simmer. Gently drop the meatballs into the broth and let them cook for about 10-15 minutes, or until cooked through and float to the
6. Gently drop in the wonton wrappers in batches, and let them cook for about 3-5 minutes, or until they float to the top. Add the bok choy and let cook for another 2-3 minutes, until wilted but still retains some texture.
7. Taste and adjust seasoning as needed (soy sauce, rice vinegar, chill oil, fish sauce, etc.)
8. Serve and garnish with a drizzle of chili oil and green onions.
